actu/urls.py
from django.urls import path

from actu import views

app_name = "actu"
urlpatterns = [
    path("", views.ActuList.as_view(), name="liste"),
    path("ajouter", views.ActuCreate.as_view(), name="add_actu"),
    path("edition/<int:pk>", views.ActuUpdate.as_view(), name="edit_actu"),
    path("supprimer/<int:pk>", views.ActuDelete.as_view(), name="delete_actu"),
]

partitions/urls.py
from django.urls import path

from . import views

app_name = "partitions"
urlpatterns = [
    path("", views.Repertoire.as_view(), name="liste"),
    path("download", views.download_musecores, name="download_musecores"),
    path("<str:nom>/<str:auteur>/upload", views.Upload.as_view(), name="upload"),
    path("<str:nom>/<str:auteur>", views.Morceau.as_view(), name="listepart"),
    path("<str:nom>/<str:auteur>/see/<int:partition_id>", views.see, name="see"),
    path("<str:nom>/<str:auteur>/<int:partition_id>", views.download, name="download"),
    path(
        "<str:nom>/<str:auteur>/<int:id>/conf",
        views.ConfDelete.as_view(),
        name="conf_delete",
    ),
    path(
        "<str:nom>/<str:auteur>/<int:id>/delete",
        views.DeletePart.as_view(),
        name="delete",
    ),
    path(
        "<str:nom>/<str:auteur>/delete", views.DeleteMorc.as_view(), name="delete_morc"
    ),
    path(
        "<str:nom>/<str:auteur>/conf",
        views.ConfDeleteMorc.as_view(),
        name="conf_delete_morc",
    ),
    path("new", views.CreateMorc.as_view(), name="ajouter_morceau"),
]

partitions/models.py
import os

from django.conf import settings
from django.db import models
from django.db.models.functions import Lower
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    name = models.CharField(max_length=127)
    order = models.IntegerField(verbose_name=_("ordre"))
    nom_en = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Categorie")
        verbose_name_plural = _("Categories")
        ordering = ("order",)


class Partition(models.Model):
    nom = models.CharField(max_length=100)
    part = models.FileField(upload_to="partitions/")
    morceau = models.ForeignKey("PartitionSet", on_delete=models.CASCADE)

    def __str__(self):
        return self.nom

    def delete(self, *args, **kwargs):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.part.name))
        super(Partition, self).delete(*args, **kwargs)

    class Meta:
        verbose_name = _("Morceau")
        verbose_name_plural = _("Morceaux")
        ordering = (Lower("nom"),)


class PartitionSet(models.Model):
    nom = models.CharField(max_length=100)
    auteur = models.CharField(max_length=100)
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, verbose_name=_("Type de partition")
    )

    infos = models.TextField(_("Infos utiles"), null=False, blank=True, default="")
    infos_en = models.TextField(
        "Infos utiles en anglais", null=False, blank=True, default=""
    )
    

    def __str__(self):
        return "%s - %s [%s]" % (self.nom, self.auteur, self.category)

    class Meta:
        verbose_name = _("Morceau")
        verbose_name_plural = _("Morceaux")
        ordering = (Lower("nom"),)

partitions/forms.py
from django import forms

from .models import PartitionSet


class UploadFileForm(forms.Form):
    file=forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': False}))


class UploadMorceauForm(forms.Form):
    titre = forms.CharField(max_length=100)
    auteur = forms.CharField(max_length=100)


class ChefEditMorceauForm(forms.ModelForm):
    class Meta:
        model = PartitionSet
        fields = ("category", "infos", "infos_en")

partitions/views.py
import io
import os
import zipfile

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files import File
from django.db.models import Q
from django.http import Http404
from django.shortcuts import HttpResponse, get_object_or_404, redirect, render
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

from gestion.mixins import ChefRequiredMixin
from gestion.models import Photo
from partitions.forms import UploadFileForm, UploadMorceauForm
from partitions.models import Category, Partition, PartitionSet

from .forms import ChefEditMorceauForm


def download_musecores(request):

    p = Partition.objects.filter(
        Q(part__contains=".mscz")
        & Q(
            Q(morceau__category__name="Partitions actives")
            | Q(morceau__category__name="Partitions optionnelles")
        )
    )

    zip_subdir = "Ossia_musescores"
    zip_filename = "%s.zip" % zip_subdir

    # Open StringIO to grab in-memory ZIP contents
    s = io.BytesIO()

    # The zip compressor
    zf = zipfile.ZipFile(s, "w")

    for part in p:
        fpath = part.part.path

        typ = ".mscz"
        # Calculate path for file in zip
        fdir, fname = os.path.split(fpath)
        zip_path = os.path.join(
            zip_subdir,
            "%s_%s_%s.%s"
            % (
                slugify(part.morceau.nom),
                slugify(part.morceau.auteur),
                slugify(part.nom),
                typ,
            ),
        )

        # Add file, at correct path
        zf.write(fpath, zip_path)

    # Must close zip for all contents to be written
    zf.close()
    # Grab ZIP file from in-memory, make response with correct MIME-type
    resp = HttpResponse(s.getvalue())
    # ..and correct content-disposition
    resp["Content-Disposition"] = "attachment; filename=%s" % zip_filename

    return resp


class Repertoire(TemplateView):
    template_name = "partitions/repertoire.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.prefetch_related(
            "partitionset_set"
        ).order_by("order")
        context["photo"] = Photo.objects.filter(cat="part").order_by("?").first()
        return context


class Morceau(LoginRequiredMixin, TemplateView):
    template_name = "partitions/part.html"
    form_class = ChefEditMorceauForm

    def get_context_data(self, **kwargs):
        context = super(Morceau, self).get_context_data(**kwargs)
        p = get_object_or_404(
            PartitionSet, nom=self.kwargs["nom"], auteur=self.kwargs["auteur"]
        )
        part = p.partition_set.all().order_by("nom")
        form = self.form_class(instance=p)
        infos = mark_safe(p.infos)
        infos_en = mark_safe(p.infos_en)

        context["p"] = p
        context["infos"] = infos
        context["infos_en"] = infos_en
        context["form"] = form
        context["part"] = part
        context["nom"] = self.kwargs["nom"]
        context["auteur"] = self.kwargs["auteur"]

        return context

    def post(self, request, *args, **kwargs):
        p = get_object_or_404(
            PartitionSet, nom=self.kwargs["nom"], auteur=self.kwargs["auteur"]
        )
        if request.user.profile.is_chef:
            form = self.form_class(request.POST, instance=p)
            if form.is_valid():
                form.save()
        context = self.get_context_data()
        return render(request, self.template_name, context)


class Upload(ChefRequiredMixin, TemplateView):
    form_class = UploadFileForm
    template_name = "partitions/upload.html"

    def get_context_data(self, **kwargs):
        context = super(Upload, self).get_context_data(**kwargs)
        form = self.form_class()

        context["nom"] = self.kwargs["nom"]
        context["auteur"] = self.kwargs["auteur"]
        context["form"] = form
        return context

    def post(self, request, *args, **kwargs):
        form = UploadFileForm(request.POST, request.FILES)
        error = False
        sauvegarde = False
        if form.is_valid():
            for file in request.FILES.getlist('file'):
                partition = Partition()
                partition.part = file
                partition.nom = file.name
                if "/" in partition.nom:
                    error = _("Le caractère / n'est pas autorisé dans le nom")
                    context = self.get_context_data()
                    context["error"] = error
                    return render(request, self.template_name, context)
                mor = get_object_or_404(
                    PartitionSet, nom=self.kwargs["nom"], auteur=self.kwargs["auteur"]
                )
                partition.morceau = mor
                try:
                    mor.partition_set.get(nom=partition.nom)
                    error = _("Un morceau du même nom existe déjà")
                except Partition.DoesNotExist:
                    partition.save()
                    sauvegarde = True

        context = self.get_context_data()
        context["form"] = form
        context["error"] = error
        context["sauvegarde"] = sauvegarde
        return render(request, self.template_name, context)


def see(request, nom, auteur, partition_id):
    partition = get_object_or_404(Partition, id=partition_id)
    _, extension = os.path.splitext(partition.part.path)

    if request.user.is_authenticated:
        if ".pdf" == extension:
            with open(partition.part.path, "rb") as f:
                myfile = File(f)
                response = HttpResponse(content=myfile.read())
                response["Content-Type"] = "application/pdf"
                response["Content-Disposition"] = "inline; filename=%s_%s_%s.pdf" % (
                    slugify(nom),
                    slugify(auteur),
                    slugify(partition.nom),
                )
            return response
        elif ".mp3" == extension:
            with open(partition.part.path, "rb") as f:
                myfile = File(f)
                response = HttpResponse()
                response.write(myfile.read())
                response["Content-Type"] = "audio/mp3"
                response["Content-Length"] = myfile.size
            return response
        else:
            p = get_object_or_404(PartitionSet, nom=nom, auteur=auteur)
            part = p.partition_set.all()
            return render(
                request,
                "partitions/part.html",
                {"p": p, "part": part, "nom": nom, "auteur": auteur},
            )
    else:
        return redirect("login")


class DeletePart(ChefRequiredMixin, TemplateView):
    model = PartitionSet

    def get(self, request, *args, **kwargs):
        p = get_object_or_404(
            self.model, nom=self.kwargs["nom"], auteur=self.kwargs["auteur"]
        )
        try:
            part = p.partition_set.get(id=self.kwargs["id"])
        except Partition.DoesNotExist:
            raise Http404
        part.delete()
        return redirect(
            "partitions:listepart", nom=self.kwargs["nom"], auteur=self.kwargs["auteur"]
        )


class CreateMorc(ChefRequiredMixin, TemplateView):
    form_class = UploadMorceauForm
    template_name = "partitions/new.html"

    def get_context_data(self, **kwargs):
        context = super(CreateMorc, self).get_context_data(**kwargs)
        context["form"] = self.form_class()
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        sauvegarde = False
        error = False
        if form.is_valid():
            partitionset = PartitionSet()
            partitionset.nom = form.cleaned_data["titre"]
            partitionset.auteur = form.cleaned_data["auteur"]
            if "/" in partitionset.auteur or "/" in partitionset.nom:
                error = _("Le caractère / n'est pas autorisé")
                context = self.get_context_data()
                context["error"] = error
                return render(request, self.template_name, context)
            try:
                PartitionSet.objects.get(
                    nom=partitionset.nom, auteur=partitionset.auteur
                )
                error = _("Un morceau du même nom existe déjà")
            except PartitionSet.DoesNotExist:
                # XXX. Hideous
                cat = Category.objects.first()
                try:
                    cat = Category.objects.get(name="Partitions à venir")
                except Category.DoesNotExist:
                    pass
                partitionset.category = cat
                partitionset.save()
                sauvegarde = True
                return redirect("partitions:liste")
        context = self.get_context_data()
        context["sauvegarde"] = sauvegarde
        context["error"] = error
        context["form"] = form
        return render(request, self.template_name, context)


class ConfDelete(ChefRequiredMixin, TemplateView):
    template_name = "partitions/conf_delete.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["nom"] = self.kwargs.get("nom")
        context["auteur"] = self.kwargs.get("auteur")
        context["id"] = self.kwargs.get("id")
        return context


class DeleteMorc(ChefRequiredMixin, TemplateView):
    model = PartitionSet

    def get(self, request, *args, **kwargs):
        p = get_object_or_404(
            self.model, nom=self.kwargs["nom"], auteur=self.kwargs["auteur"]
        )

partitions/templates/partitions/conf_delete.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% block titre %}{% trans "Confirmer supression" %}{% endblock %}
{% block content %}
<section id="create" class="main style3 secondary">
  <div class="content">

  <div style="float:left;width:70%;text-align:center;background:#ffff;align:center">
<div style="width:90%;text-align:left;display: inline-block;">
    </p>
<h4>{% trans "Confirmation de suppression" %}</h4>
<p>{% trans "Voulez-vous vraiment supprimer cette partition ?" %}</p>
<p><a href="{% url "partitions:delete" nom auteur id %}" ><button>{% trans "Oui" %}</button></a></p>
<p><a href="{% url "partitions:listepart" nom auteur %}" ><button>{% trans "Retour à la liste des partitions" %}</button></a></p>

</div>
</div>
</div>
</section>

{% endblock %}

partitions/templates/partitions/conf_delete_morc.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% block titre %}{% trans "Confirmation de suppression" %}{% endblock %}
{% block content %}
<section id="create" class="main style3 secondary">
  <div class="content">

  <div style="float:left;width:70%;text-align:center;background:#ffff;align:center">
<div style="width:90%;text-align:left;display: inline-block;">
    </p>
<h4>{% trans "Confirmation de suppression :" %}</h4>
<p>{% blocktrans with nom=nom auteur=auteur %}Voulez-vous vraiment supprimer {{ nom }}-{{ auteur }} et toutes les partitions qu'il contient ?{% endblocktrans %}</p>
<p><a href="{% url "partitions:delete_morc" nom auteur %}"><button>{% trans "Oui" %}</button></a></p>
<p><a href="{% url "partitions:liste" %}"><button>{% trans "Retour à la liste des partitions" %}</button></a></p>
</div>
</div>
</div>
</section>
{% endblock %}

partitions/templates/partitions/liste.html
{% extends "gestion/base.html" %}

{% block titre %}Liste des partitions{% endblock %}

{% block content %}
<section id="orchestre" class="main style2 right dark fullscreen">
	<div class="content box style2">
		<header>
  <h1>Liste des partitions</h1>
  		</header>
  {% if suppression %}
    <p>{{ suppression }}</p>
  {% endif %}

  {% if user.is_authenticated %}
    <h3><a href="{% url "partitions:ajouter_morceau" %}">{% trans "Ajouter un morceau" %}</a></h3>
  {% endif %}

  {% for category in categories %}
    <h3 class="part">{{ category }}</h3>
    <ul class="filelist">
    {% for partition in category.partitionset_set.all %}
      <li>
        {% if not user.is_authenticated %}
          {{ partition.nom }} - {{ partition.auteur }}
        {% else %}
          <a href="{% url "partitions:listepart" partition.nom partition.auteur %}"
             class="fichier">{{ partition.nom }} - {{ partition.auteur }}</a>
        {% endif %}
        {% if user.profile.is_chef %}
          <a href="{% url "partitions:conf_delete_morc" partition.nom partition.auteur %}"
             class="supprimer">{% trans "Supprimer" %}</a>
        {% endif %}
      </li>
    {% endfor %}
    </ul>
  {% endfor %}

  								</div>
  							</section>
{% endblock %}

partitions/templates/partitions/new.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% block titre %}{% trans "Ajouter un morceau" %}{% endblock %}
{% block content %}
<section id="create" class="main style3 secondary">
  <div class="content">

  <div style="float:left;width:70%;text-align:center;background:#ffff;align:center">
<div style="width:90%;text-align:left;display: inline-block;">
<p/>
<h4>{% trans "Ajouter un morceau" %} :</h4>
{% if sauvegarde %}
<p>{% trans "Morceau créé" %}"</p>
{% endif %}
{% if error %}
<p> {{ error }}</p>
{% endif %}

    <form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Ajouter" %}"/> &nbsp<a href="{% url 'partitions:liste' %}"><button>{% trans "Retour à la liste" %}</button></a>
    </form>
</div>
</div>
</div>


</section>

{% endblock %}

partitions/templates/partitions/part.html
{% extends "gestion/base.html" %}
{% load static %}
{% load i18n %}
{% block titre %}{{p}}{% endblock %}
{% get_current_language as current_language %}
{% load autotranslate %}
{% block content %}
<section id="create" class="main style3 secondary">
  <div class="content">
<div style="float:left;width:40%;">
					<h4>{{p.nom}} - {{p.auteur}} [{% autotranslate current_language p.category.name p.category.nom_en %}] :</h4>

					{% if suppression %}
			<p>{{ suppression }}</p>
	{% endif %}


							<div class="table-wrapper">

								<table style="background: rgb(102, 153, 255);">
									<tbody>
										{% for p in part %}
										{% if user.is_authenticated and ".mscz" in p.part.url %}
										<td width="60%"><p class="fichier">{{ p.nom }}</p></td>


											{% if user.is_authenticated %}
										<td width="20%"> <a href="{% url "partitions:download" nom auteur p.id %}"><button>{% trans "Télécharger" %}</button></a></td>
											{% endif %}
										{% if user.profile.is_chef %}	<td width="20%">
									<a href="{% url "partitions:conf_delete" nom auteur p.pk %}"><button>{% trans "Supprimer" %}</button></a></td>
										{% endif %}
										{% endif %}
										{% endfor %}
                      {% for p in part %}
											{% if user.is_authenticated and not ".mscz" in p.part.url %}
										<tr>
                      {% if user.is_authenticated and ".pdf" in p.part.url %}
                      <td><a href="{% url "partitions:see" nom auteur p.id %}" class="fichier">{{ p.nom }}</a></td>
                        {% elif user.is_authenticated and ".mp3" in p.part.url %}
                        <td><a href="{% url "partitions:see" nom auteur p.id %}" class="fichier">{{ p.nom }}</a></td>

                          {% else %}
                          <td><p class="fichier">{{ p.nom }}</p></td>
                            {% endif %}

                            {% if user.is_authenticated %}
                          <td> <a href="{% url "partitions:download" nom auteur p.id %}"><button>{% trans "Télécharger" %}</button></a></td>
                            {% endif %}
													{% if user.profile.is_chef %}	<td>
            						<a href="{% url "partitions:conf_delete" nom auteur p.pk %}"><button>{% trans "Supprimer" %}</button></a></td>
        					{% endif %}
										</tr>
										{% endif %}
										{% empty %}
										<p> {% blocktrans %}Pas de partitons pour le moment !{% endblocktrans %} </p>
									{% endfor %}
							</tbody>
						</table>
	 <a href="{% url "partitions:liste" %}"><button>{% trans "Retour au répertoire" %}</button></a>
						{% if user.profile.is_chef %}
						 <a href="{% url "partitions:upload" p.nom p.auteur %}"><button>{% trans "Ajouter des fichiers" %}</button></a>

						{% if infos or infos_en %}

							<h3>{% trans "Infos utiles :" %}</h3>

						 <div class="box">{% autotranslate current_language infos infos_en %}</div>


						{% endif %}

							{% endif %}
					</div>
</div>
<div style="float:right;width:50%;">
							{% if user.profile.is_chef %}
              <div class="box" style="background:#ffff">

			<form action="{% url "partitions:listepart" nom auteur %}" id="chef-edit-form" method="post">
					{% csrf_token %}
					{{ form.as_p }}
					<input type="submit" value="Enregister" />
			</form>
      </div>

	{% else %}
                {% if infos or infos_en %}
					<h3>{% trans "Infos utiles :" %}</h3>
				 <div class="box">{% autotranslate current_language infos infos_en %}</div>
{% endif %}

{% endif %}


			</div>

      			</div>

		</section>

      {% endblock %}

partitions/templates/partitions/repertoire.html
{% extends "gestion/base.html" %}
{% load static %}
{% load i18n %}
{% load autotranslate %}
{% load halflength %}
{% block titre %}{% trans "Ossia : répertoire" %}{% endblock %}
{% block content %}

<section id="intro" class="main style1 dark fullscreen">
  <div class="content">
    <header>
      <h2 style="color:#ffff">Répertoire de Ossia</h2>
      </header>
    {% if user.profile.is_chef %}
    <a href="{% url "partitions:ajouter_morceau" %}"><button>{% trans "Ajouter un morceau" %}</button></a> &nbsp <a href="{% url "partitions:download_musecores" %}"><button>{% trans "Télécharger tous les musecores actifs" %}</button></a>
    {% elif user.is_authenticated %}
     <a href="{% url "partitions:download_musecores" %}"><button>{% trans "Télécharger tous les musecores actifs" %}</button></a>
    {% endif %}
    <footer>
      <a href="#orchestre" class="button style2 down">Plus</a>
    </footer>
  </div>
</section>


        {% for category in categories %}

  {% if forloop.counter0|divisibleby:2 %}

<section id="orchestre" class="main style2 left dark fullscreen">
<div class="content boxpop style2">
  {% else %}
  <section id="bureau" class="main style2 right dark fullscreen">
    <div class="content boxpop style2">
  {% endif %}


        		<header>

          <h4>{% autotranslate current_language category.name category.nom_en %} :</h4>
  		</header>

                  <div class="table-wrapper">
    								<table class="default">
    									<thead>
    										<tr>
    											<th>{% trans "Morceau" %}</th>
    											<th>{% trans "Compositeur" %}</th>
    										</tr>
    									</thead>
                      	<tbody>
                          {% with rep=category.partitionset_set.all %}

                            {% for partition in rep %}

                                {% if not user.is_authenticated %}
                            <tr>
                              <td>  {{ partition.nom }} </td>
                              <td> {{ partition.auteur }} </td>
                            </tr>
                              {% else %}
                              <tr>
                                <td>  <u><a href="{% url "partitions:listepart" partition.nom partition.auteur %}"
             class="fichier">{{ partition.nom }}</a> </td>
                                <td> {{ partition.auteur }}  </a></u> </td>
                                {% if user.profile.is_chef %}<td>

                                   <a href="{% url "partitions:conf_delete_morc" partition.nom partition.auteur %}"
            ><button>{% trans "Supprimer" %}</button></a></td>

                                {% endif %}

                              </tr>

                            {% endif %}


                            {% endfor %}
                            {% endwith %}

                        </tbody>
                    </table>
                  </div>


            </div>


          </section>
        {% endfor %}


{% endblock %}

partitions/templates/partitions/upload.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% block titre %}{% trans "Ajout de parties" %}{% endblock %}
{% block content %}
<section id="create" class="main style3 secondary">
  <div class="content">

  <div style="float:left;width:70%;text-align:center;background:#ffff;align:center">
<div style="width:90%;text-align:left;display: inline-block;">
    </p>
<h4>{% trans "Ajouter une partition :" %} </h4>
{% if sauvegarde %}
<p>Partition enregistrée</p>
{% endif %}
{% if error %}
<p>{{ error }}</p>
{% endif %}
<div class="row">
    <div class="6u 12u$(small)">
<p>
    <form method ="post" enctype="multipart/form-data" action="{% url 'partitions:upload' nom auteur %}">
    {% csrf_token %}
    {{ form.as_p }}
<p>    <input type="submit" value="{% trans "Enregistrer"%}"/> </p>
    </form>
</p>
<p><a href="{% url "partitions:listepart" nom auteur %}"><button>{% trans "Retour aux partitions" %}</button></a></p>
</div>
</div>
</div>
</section>
{% endblock %}