Ossia/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from gestion import views as gestion_views

urlpatterns = []
urlpatterns += i18n_patterns(
    path("", gestion_views.Home.as_view(), name="home"),
    path("registration", gestion_views.Inscription.as_view(), name="registration"),
    path("rejoins", gestion_views.Rejoins.as_view(), name="rejoins"),
    path("change", gestion_views.ChangeMembre.as_view(), name="change_membre"),
    path("password", gestion_views.ChangePassword.as_view(), name="change_password"),
    path("thanks", gestion_views.Thanks.as_view(), name="thanks"),
    path("social", gestion_views.Social.as_view(), name="social"),
    path("chef", gestion_views.Chef.as_view(), name="chef"),
    path("profil", gestion_views.Profil.as_view(), name="profile"),
    path("changename", gestion_views.ChangeName.as_view(), name="change-doodle-name"),
    path("logout", auth_views.LogoutView.as_view(next_page="home"), name="logout"),
    path("login", gestion_views.MyLoginView.as_view(), name="login"),
    path("agenda/", include("calendrier.urls", namespace="calendrier")),
    path("partitions/", include("partitions.urls")),
    path(
        "admin/",
        admin.site.urls,
    ),
    path("trombonoscope/", include("trombonoscope.urls")),
    path("actu/", include("actu.urls")),
    path("avatar/", include("avatar.urls")),
    path("photos", gestion_views.PhotoList.as_view(), name="liste_photo"),
    path("add_photo", gestion_views.PhotoCreate.as_view(), name="add_photo"),
    path(
        "photo_edition/<int:pk>", gestion_views.PhotoUpdate.as_view(), name="edit_photo"
    ),
    path(
        "photo_delete/<int:pk>",
        gestion_views.PhotoDelete.as_view(),
        name="delete_photo",
    ),
    path("videos", gestion_views.VideoList.as_view(), name="liste_video"),
    path("add_video", gestion_views.VideoCreate.as_view(), name="add_video"),
    path(
        "video_edition/<int:pk>", gestion_views.VideoUpdate.as_view(), name="edit_video"
    ),
    path(
        "video_delete/<int:pk>",
        gestion_views.VideoDelete.as_view(),
        name="delete_video",
    ),
    prefix_default_language=False,
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

actu/urls.py
from django.urls import path

from actu import views

app_name = "actu"
urlpatterns = [
    path("", views.ActuList.as_view(), name="liste"),
    path("ajouter", views.ActuCreate.as_view(), name="add_actu"),
    path("edition/<int:pk>", views.ActuUpdate.as_view(), name="edit_actu"),
    path("supprimer/<int:pk>", views.ActuDelete.as_view(), name="delete_actu"),
]

calendrier/urls.py
from django.urls import path

from . import views
from .views import EventDelete, EventUpdate

app_name = "calendrier"
urlpatterns = [
    path("", views.Agenda.as_view(), name="liste"),
    path("calendar", views.Home.as_view(), name="home"),
    path("new", views.CreateEvent.as_view(), name="create_event"),
    path("edition/<int:pk>", EventUpdate.as_view(), name="edit_event"),
    path("supprimer/<int:pk>", EventDelete.as_view(), name="delete_event"),
    path("<int:id>/changename", views.ChangeName.as_view(), name="change-doodle-name"),
    path("<int:id>/reponse", views.ReponseEvent.as_view(), name="reponse"),
    path("<int:pYear>/<int:pMonth>", views.Calendar.as_view(), name="view-month"),
    path("<int:id>", views.ViewEvent.as_view(), name="view-event"),
]

partitions/urls.py
from django.urls import path

from . import views

app_name = "partitions"
urlpatterns = [
    path("", views.Repertoire.as_view(), name="liste"),
    path("download", views.download_musecores, name="download_musecores"),
    path("<str:nom>/<str:auteur>/upload", views.Upload.as_view(), name="upload"),
    path("<str:nom>/<str:auteur>", views.Morceau.as_view(), name="listepart"),
    path("<str:nom>/<str:auteur>/see/<int:partition_id>", views.see, name="see"),
    path("<str:nom>/<str:auteur>/<int:partition_id>", views.download, name="download"),
    path(
        "<str:nom>/<str:auteur>/<int:id>/conf",
        views.ConfDelete.as_view(),
        name="conf_delete",
    ),
    path(
        "<str:nom>/<str:auteur>/<int:id>/delete",
        views.DeletePart.as_view(),
        name="delete",
    ),
    path(
        "<str:nom>/<str:auteur>/delete", views.DeleteMorc.as_view(), name="delete_morc"
    ),
    path(
        "<str:nom>/<str:auteur>/conf",
        views.ConfDeleteMorc.as_view(),
        name="conf_delete_morc",
    ),
    path("new", views.CreateMorc.as_view(), name="ajouter_morceau"),
]

trombonoscope/urls.py
from django.urls import path

from trombonoscope import views

app_name = "trombonoscope"
urlpatterns = [
    path("", views.Trombonoscope.as_view(), name="view"),
    path("modif_profil", views.ChangeTrombonoscope.as_view(), name="change"),
]

gestion/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from gestion.models import OssiaUser


class RegistrationFormUser(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "password1",
            "password2",
            "email",
        )


class ChangeFormUser(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
        )


class ChangeMembreForm(forms.ModelForm):
    def clean(self):
        cleaned_data = super(ChangeMembreForm, self).clean()
        instru = cleaned_data.get("instru")
        instru_autre = cleaned_data.get("instru_autre")
        if (instru == "Autre") and not (instru_autre):
            raise forms.ValidationError(_("Préçisez quel autre instrument"))

        return cleaned_data

    class Meta:
        model = OssiaUser
        fields = (
            "phone",
            "instru",
            "instru_autre",
        )


class InscriptionMembreForm(ChangeMembreForm):
    validation = forms.CharField(max_length=100, widget=forms.PasswordInput)

    class Meta:
        model = OssiaUser
        fields = (
            "phone",
            "instru",
            "instru_autre",
        )

gestion/views.py
import random
import string

from django.conf import settings
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (CreateView, DeleteView, ListView,
                                  TemplateView, UpdateView)
import os

from calendrier.forms import ChangeDoodleName
from gestion.forms import (ChangeFormUser, ChangeMembreForm,
                           InscriptionMembreForm, RegistrationFormUser)
from gestion.mixins import ChefRequiredMixin
from gestion.models import OssiaUser, Photo, VideoGallery
from partitions.models import Category


def generer(*args):
    caracteres = string.ascii_letters + string.digits
    aleatoire = [random.choice(caracteres) for i in range(6)]
    return "".join(aleatoire)


class Home(TemplateView):
    template_name = "gestion/index.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("calendrier:home")
        return super(Home, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.filter(
            name="Partitions actives"
        ).prefetch_related("partitionset_set")
        context["videos"] = VideoGallery.objects.all().order_by("order")
        context["photo_rep"] = (
            Photo.objects.filter(cat="home_rep").order_by("?").first()
        )
        context["photo_join"] = (
            Photo.objects.filter(cat="home_join").order_by("?").first()
        )
        context["photo_contact"] = (
            Photo.objects.filter(cat="home_contact").order_by("?").first()
        )
        return context


class MyLoginView(LoginView):

    template_name = "gestion/login.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["photo"] = Photo.objects.filter(cat="login").order_by("?").first()
        return context


class Rejoins(TemplateView):
    template_name = "gestion/rejoins.html"

class Thanks(TemplateView):
    template_name = "gestion/thanks.html"


class Social(LoginRequiredMixin, TemplateView):
    template_name = "gestion/social.html"


class Profil(LoginRequiredMixin, TemplateView):
    template_name = "gestion/profile.html"


class Chef(ChefRequiredMixin, TemplateView):
    template_name = "gestion/chef.html"


class ChangeName(LoginRequiredMixin, TemplateView):
    form_class = ChangeDoodleName
    template_name = "gestion/changename.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class(instance=self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        requbis = request.POST.copy()
        form = self.form_class(requbis, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("change_membre")

        context = self.get_context_data()
        context["form"] = form
        return render(request, self.template_name, context)


class ChangeMembre(LoginRequiredMixin, TemplateView):
    comp_form_class = ChangeMembreForm
    user_form_class = ChangeFormUser
    template_name = "gestion/change.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comp_form = self.comp_form_class(instance=self.request.user.profile)
        user_form = self.user_form_class(instance=self.request.user)
        context["comp_form"] = comp_form
        context["user_form"] = user_form
        context["photo"] = (
            Photo.objects.filter(cat="change_membre").order_by("?").first()
        )
        return context

    def post(self, request, *args, **kwargs):
        success = False
        comp_form = self.comp_form_class(request.POST, instance=request.user.profile)
        user_form = self.user_form_class(request.POST, instance=request.user)
        if user_form.is_valid() and comp_form.is_valid():
            user_form.save()
            comp_form.save()
            success = True

        context = self.get_context_data()
        context["success"] = success
        context["comp_form"] = comp_form
        context["user_form"] = user_form
        return render(request, self.template_name, context)


class ChangePassword(LoginRequiredMixin, TemplateView):
    form_class = PasswordChangeForm
    template_name = "gestion/changepasswd.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class(self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        requbis = request.POST.copy()
        success = False
        form = self.form_class(request.user, data=requbis)
        if form.is_valid():
            form.save()
            success = True
        context = self.get_context_data()
        context["success"] = success
        context["form"] = form
        return render(request, self.template_name, context)


class Inscription(TemplateView):
    user_form_class = RegistrationFormUser
    comp_form_class = InscriptionMembreForm
    template_name = "gestion/registration.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comp_form"] = self.comp_form_class()
        context["user_form"] = self.user_form_class()
        context["photo"] = (
            Photo.objects.filter(cat="inscription_membre").order_by("?").first()
        )
        return context

    def post(self, request, *args, **kwargs):
        user_form = self.user_form_class(request.POST)
        comp_form = self.comp_form_class(request.POST)
        if user_form.is_valid() and comp_form.is_valid():

            if not (
                comp_form.cleaned_data["validation"] == settings.ACCOUNT_CREATION_PASS
            ):
                error = _("Le champ Validation ne correspond pas à celui attendu")
                context = self.get_context_data()
                context["user_form"] = user_form
                context["comp_form"] = comp_form
                context["error"] = error
                return render(request, self.template_name, context)
            member = user_form.save(commit=False)
            temp = True
            while temp:
                code = generer()
                try:
                    OssiaUser.objects.get(slug=code)
                except OssiaUser.DoesNotExist:
                    temp = False
            member.save()
            (profile, k) = OssiaUser.objects.get_or_create(user=member, slug=code)
            comp_form = self.comp_form_class(request.POST, instance=profile)
            obj = comp_form.save(commit=False)
            obj.slug = code
            obj.save()
            return redirect("thanks")
        else:
            context = self.get_context_data()
            context["user_form"] = user_form
            context["comp_form"] = comp_form
            return render(request, self.template_name, context)


class PhotoList(ChefRequiredMixin, ListView):
    model = Photo
    context_object_name = "photos"
    ordering = "cat"
    template_name = "gestion/photo.html"


class PhotoCreate(ChefRequiredMixin, CreateView):
    model = Photo
    fields = ["name", "cat", "auteur", "url", "color", "image"]
    template_name = "gestion/create_photo.html"
    success_url = reverse_lazy("liste_photo")

    def form_valid(self, form):
        photo = form.save(commit=False)
        photo.save()
        return HttpResponseRedirect(self.success_url)


class PhotoUpdate(ChefRequiredMixin, UpdateView):
    model = Photo
    fields = ["name", "cat", "auteur", "url", "color", "image"]
    template_name = "gestion/update_photo.html"
    success_url = reverse_lazy("liste_photo")


class PhotoDelete(ChefRequiredMixin, DeleteView):
    model = Photo
    template_name = "gestion/delete_photo.html"
    success_url = reverse_lazy("liste_photo")


class VideoList(ChefRequiredMixin, ListView):
    model = VideoGallery
    ordering = "order"
    context_object_name = "videos"
    template_name = "gestion/video.html"


class VideoCreate(ChefRequiredMixin, CreateView):
    model = VideoGallery
    fields = ["name", "url", "order"]
    template_name = "gestion/create_video.html"
    success_url = reverse_lazy("liste_video")

    def form_valid(self, form):
        video = form.save(commit=False)
        video.save()
        return HttpResponseRedirect(self.success_url)


class VideoUpdate(ChefRequiredMixin, UpdateView):
    model = VideoGallery
    fields = ["name", "url", "order"]
    template_name = "gestion/update_video.html"
    success_url = reverse_lazy("liste_video")


class VideoDelete(ChefRequiredMixin, DeleteView):
    model = VideoGallery
    template_name = "gestion/delete_video.html"
    success_url = reverse_lazy("liste_video")

gestion/templates/gestion/base.html
{% load static %}
{% load i18n %}
{% load changelang %}
{% load avatar_tags %}
{% get_current_language as current_language %}

<!DOCTYPE HTML>
<!--
	Big Picture by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="shortcut icon" href="{% static 'images/logoround.ico' %}">
<meta charset="utf-8" />
<title>{% block titre %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
{% block extrahead %}{% endblock %}
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
			<a href="{% url 'home' %}">	<img src="{% static 'images/logo.png' %}" style="width:auto; height:3em"/></a>
				<nav>
					<ul>
						{% if not user.is_authenticated %}
						<li><a href="{% url 'home' %}#orchestre">{% trans "L'orchestre" %}</a></li>
						<li><a href="{% url 'home' %}#bureau">{% trans "Le bureau" %}</a></li>
						<li><a href="{% url 'home' %}#chef">{% trans "La direction musicale" %}</a></li>
						<li><a href="{% url 'calendrier:liste' %}">{% trans "Galerie" %}</a></li>
						<li><a href="{% url 'home' %}#rejoindre">{% trans "Rejoindre" %}</a></li>
						<li><a href="{% url 'home' %}#contact">{% trans "Contact" %}</a></li>
						<li><a href="{% url 'calendrier:liste' %}">{% trans "Concerts" %}</a></li>
						<li><a href="{% url 'calendrier:liste' %}">{% trans "Affiches" %}</a></li>
						<li><a href="{% url 'login' %}"><button>{% trans "Se connecter" %}</button></a></li>
						{% else %}
						<li><a href="{% url 'partitions:liste' %}">{% trans "Repertoire" %}</a></li>
						<li><a href="{% url 'home' %}">{% trans "Calendrier" %}</a></li>
						<li>  <a  href="{% url 'trombonoscope:view' %}">{% trans "Trombonoscope" %}</a></li>
						<li><a href="{% url 'logout' %}"><button>{% trans "Se déconnecter" %}</button></a></li>
						{% if user.profile.is_chef %}
					<li>	<a href="{% url 'actu:liste' %}">{% trans "Modifier les actualités" %}</a></li>
						{% endif %}
							{% endif %}
						{% if current_language == "fr" %}
						<li><a href="{% changelang "en" %}" ><img src="{% static 'images\en_flag.png' %}" width="60" height="40" style="vertical-align: middle"></a></li>
						{% else %}
						<li><a href="{% changelang "fr" %}" ><img src="{% static 'images\fr_flag.png' %}" width="60" height="40" style="vertical-align: middle"></a></li>
						{% endif %}
					</ul>
				</nav>
			</header>


      {% block content %}
      {% endblock %}

			<!-- Footer -->
				<footer id="footer">

					<!-- Icons -->
						<ul class="icons">
							<li><a href="https://www.facebook.com/Ossia-harmonie-de-PSL-110119993861351" target="_blank" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
							<li><a href="harmonie_psl@lists.ens.psl.eu" class="icon fa-envelope"><span class="label">Email</span></a></li>
						</ul>

				</footer>

			<!-- Scripts -->
				<script src="{% static 'assets/js/jquery.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.poptrox.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
				<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
				<script src="{% static 'assets/js/browser.min.js' %}"></script>
				<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
				<script src="{% static 'assets/js/util.js' %}"></script>
				<script src="{% static 'assets/js/main.js' %}"></script>

			<script type="text/javascript">


		function ouvrirFermerSpoiler(div)
		{
				var divContenu = div.getElementsByTagName('div')[1];


				if(divContenu.style.display == 'block')
						divContenu.style.display = 'none';
				else
						divContenu.style.display = 'block';
		}

</script>
{% block script %}
{% endblock %}
	</body>
</html>

gestion/templates/gestion/change.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% load static %}
{% block titre %}{% trans "Modification du profil" %}{% endblock %}

{% block content %}
<section id="wrapper" >
  <section class="wrapper style1" >
  <div class="inner">
      <div class="content">
<h2>{% trans "Modification du profil" %} :</h2>
{% if error %}
<p>{{ error }}</p>
{% endif %}
{% if success %}
<p>{% trans "Changements enregistrés" %} !</p>
{% endif %}
<p><a href="{% url "change_password" %}" class="button">{% trans "Changer mon mot de passe" %}</a> &nbsp <a href="{% url "change-doodle-name" %}" class="button">{% trans "Changer mon nom pour les doodles" %}</a></p>
<form action="{% url 'change_membre' %}" method="post">
    {% csrf_token %}
    {{ comp_form.non_field_errors }}
    {{ user_form.as_p }}
    {% for field in comp_form %}
 <div class="fieldWrapper">
        {{ field.errors }}


        {% if field.id_for_label == "id_instru_autre" %}
  <div id="instru_autre_field" {% if comp_form.instru.value != "Autre" %} style="display: none; "{% endif %}>
{% elif field.id_for_label == "id_instru_bonus" %}
  <div id="instru_bonus_field" {% if comp_form.multi_instrumentiste.value == "Non" %} style="display: none; "{% endif %}>
{% else %}
  <div>
{% endif %}
     <p>{{ field.label_tag }}
        {{ field }}	{% if field.help_text %}
        {{ field.help_text|safe }}
            {% endif %}</p>
</div>




</div>

{% endfor %}

    <input type="submit" value="{% trans "Valider" %}" /> &nbsp; <a href="{% url 'home' %}" class="button alt">{% trans "Retour à l'acceuil" %}</a>
</form>

</div>
</div>
</section>
</section>

{% endblock %}

gestion/templates/gestion/changename.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% block titre %}{% trans "Modification du profil" %}{% endblock %}

{% block content %}
<section id="wrapper" >
  <section class="wrapper style1" >
  <div class="inner">
      <div class="content">
<h2>{% trans "Modification du profil" %} :</h2>
{% if error %}
<p>{{ error }}</p>
{% endif %}
{% if success %}
<p>{% trans "Changement enregistré" %} !</p>
{% endif %}
<form action="{% url 'change-doodle-name' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Valider" %}" />
</form>
</div>
</div>

</section>
</section>
{% endblock %}

gestion/templates/gestion/changepasswd.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% block titre %}{% trans "Changement du mot de passe" %}{% endblock %}

{% block content %}
<section id="wrapper" >
  <section class="wrapper style1" >
  <div class="inner">
      <div class="content">
<h2>{% trans "Changement du mot de passe" %} :</h2>
{% if error %}
<p>{{ error }}</p>
{% endif %}
{% if success %}
<p>{% trans "Changement enregistré" %} !</p>
{% endif %}
<form action="{% url 'change_password' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Valider" %}" /> &nbsp <a href="{% url 'change_membre' %}" class="button alt">{% trans "Retour" %}</a>
</form>
</div></div></section></section>
{% endblock %}

gestion/templates/gestion/chef.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% block titre %}{% trans "Cheff·e·s" %}{% endblock %}

{% block content %}
<section id="wrapper" >
  <section class="wrapper style1" >
  <div class="inner">
      <div class="content">
<h2>{% trans "Le pouvoir des cheff·e·s" %} :</h2>
<ul>
  <li>  <a href="/admin/">{% trans "Administration" %}</a></li>
  <li>  <a href="{% url 'calendrier:create_event' %}">{% trans "Ajouter un événement" %}</a></li>
    <li><a href="{% url 'actu:liste' %}">{% trans "Modifier les actualités" %}</a></li>
      <li><a href="{% url 'liste_photo' %}">{% trans "Modifier les photos" %}</a></li>
        <li><a href="{% url 'liste_video' %}">{% trans "Modifier les vidéos" %}</a></li>
  </ul>

</div>
</div>

</section>
</section>
{% endblock %}

gestion/templates/gestion/create_video.html
{% extends "gestion/base.html" %}
{% load i18n %}
{%block titre %}{% trans "Ajout d'une vidéo" %}{% endblock %}

{% block content %}
<section id="wrapper" >
  <section class="wrapper style1" >
  <div class="inner">
      <div class="content">
<p><a href="{% url "liste_video" %}" class="button alt">{% trans "Retour à la liste" %}</a></p>
{% if envoi %}<p>{% trans "Cette vidéo à été enregistrée" %}.{% endif %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Enregistrer" %}" />
</form>
</div>
</div>
</section>
</section>
{% endblock %}

gestion/templates/gestion/delete_photo.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% block titre %}{% trans "Suppression d'une photo" %}{% endblock %}
{% block content %}
<section id="wrapper" >
  <section class="wrapper style1" >
  <div class="inner">
      <div class="content">
<form action="" method="post">
    {% csrf_token %}
<p><a href="{% url "liste_photo" %}" class="button alt">{% trans "Retour aux photos" %}</a></p>
    <p>{% blocktrans with object=object %} Voulez vous vraiment supprimer la photo {{ object.name }}?{% endblocktrans %}</p>
    <input type="submit" value="{% trans "Oui" %}" />
</form>
</div></div></section>
</section>
{% endblock %}

gestion/templates/gestion/delete_video.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% block titre %}{% trans "Suppression d'une vidéo" %}{% endblock %}
{% block content %}
<section id="wrapper" >
  <section class="wrapper style1" >
  <div class="inner">
      <div class="content">
<form action="" method="post">
    {% csrf_token %}
<p><a href="{% url "liste_video" %}" class="button alt">{% trans "Retour aux vidéos" %}</a></p>
    <p>{% blocktrans with object=object %} Voulez vous vraiment supprimer la vidéo {{ object.name }}?{% endblocktrans %}</p>
    <input type="submit" value="{% trans "Oui" %}" />
</form>
</div></div></section>
</section>
{% endblock %}

gestion/templates/gestion/divers.html
{% extends "gestion/base.html" %}
{% block titre %}Divers{% endblock %}
{% block content %}
<section id="wrapper" >
  <section class="wrapper style1" >
  <div class="inner">
      <div class="content">
<h1>Divers</h1>
<ul>
<li><a href="{% url "propositions:list" %}">Propositions de morceaux</a></li>
<li><a href="{% url "pads:list" %}">Pads</a></li>
</ul>
</div>
</div>
</section>
</section>
{% endblock %}

gestion/templates/gestion/profile.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% block titre %}{% trans "Profil" %}{% endblock %}

{% block content %}
<section id="wrapper" >
  <section class="wrapper style1" >
  <div class="inner">
      <div class="content">
<h2>{% trans "Profil" %} :</h2>
<ul>
  <li>  <a href="{% url 'change_membre' %}">{% trans "Modifier le profil" %}</a></li>
  <li> <a href="{% url 'trombonoscope:change' %}">{% trans "Modifier le Trombo" %}</a></li>
    <li><a href="{% url 'logout' %}">{% trans "Déconnexion" %}</a></li>
  </ul>

</div>
</div>
</section>
</section>
{% endblock %}

gestion/templates/gestion/thanks.html
{% extends "gestion/base.html" %}
{% load static %}
{% load i18n %}
{% block extrahead %}
        <!-- CSS -->


{% endblock %}
{% block titre %}{% trans "L'Ernestophone" %}{% endblock %}
{% block content %}
<section id="orchestre" class="main style2 right dark fullscreen">
	<div class="content box style2">

		<header>
    <h2>{% trans "Bienvenue !!" %}</h2>
	</header>

        <p>  {% trans "Ton inscription a bien été validée !" %}</p>
          <a href="{% url 'login' %}" class="button big " >{% trans "Connecte toi !" %}</a> </div>
        </div>

      </section>
  {% endblock %}