actu/urls.py
from django.urls import path

from actu import views

app_name = "actu"
urlpatterns = [
    path("", views.ActuList.as_view(), name="liste"),
    path("ajouter", views.ActuCreate.as_view(), name="add_actu"),
    path("edition/<int:pk>", views.ActuUpdate.as_view(), name="edit_actu"),
    path("supprimer/<int:pk>", views.ActuDelete.as_view(), name="delete_actu"),
]

actu/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Actu(models.Model):

    text = models.TextField(_("Info"), null=True, blank=False)
    text_en = models.TextField(("Info en anglais"), null=True, blank=True)
    order = models.IntegerField(verbose_name=_("ordre"))

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = _("Actualité")
        verbose_name_plural = _("Actualités")
        ordering = ("order",)

actu/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from actu.models import Actu
from gestion.mixins import ChefRequiredMixin


class ActuList(ChefRequiredMixin, ListView):
    model = Actu
    context_object_name = "actus"
    template_name = "actu/actualité.html"


class ActuCreate(ChefRequiredMixin, CreateView):
    model = Actu
    fields = ["text", "order", "text_en"]
    template_name = "actu/create_actu.html"
    success_url = reverse_lazy("actu:liste")

    def form_valid(self, form):
        actu = form.save(commit=False)
        actu.save()
        return HttpResponseRedirect(self.success_url)


class ActuUpdate(ChefRequiredMixin, UpdateView):
    model = Actu
    fields = ["text", "order", "text_en"]
    template_name = "actu/update_actu.html"
    success_url = reverse_lazy("actu:liste")


class ActuDelete(ChefRequiredMixin, DeleteView):
    model = Actu
    template_name = "actu/delete_actu.html"
    success_url = reverse_lazy("actu:liste")

actu/templates/actu/actualité.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% get_current_language as current_language %}
{% load autotranslate %}
{% block titre %}{% trans "Liste des actualités" %}{% endblock %}
{% block content %}

<section id="create" class="main style3 secondary">
  <div class="content">

  <div style="float:left;width:70%;text-align:center;background:#ffff;align:center">
<div style="width:90%;text-align:left;display: inline-block;">
  <p/>
  <h4>{% trans "Liste des actualités" %} :</h4>


    <p><a href="{% url "actu:add_actu" %}" class="button">{% trans "Ajouter une actualité" %}</a></p>

  <ul class="filelist">
  {% for a in actus %}
    <li>
      <p>{% autotranslate current_language a.text a.text_en %}   &nbsp <a class="button alt" href="{% url "actu:edit_actu" a.id %}">{% trans "Modifier" %}</a>
      &nbsp <a class="button alt" href="{% url "actu:delete_actu" a.id %}">{% trans "Supprimer" %}</a></p>
</li>

  {% empty %}
    <p>{% trans "Pas d'actualités pour le moment" %}</p>
  {% endfor %}
  </ul>
</div></div></div></section></section>
{% endblock %}

actu/templates/actu/create_actu.html
{% extends "gestion/base.html" %}
{% load i18n %}
{%block titre %}{% trans "Ajout d'une actualité" %}{% endblock %}

{% block content %}

<section id="create" class="main style3 secondary">
  <div class="content">

  <div style="float:left;width:70%;text-align:center;background:#ffff;align:center">
<div style="width:90%;text-align:left;display: inline-block;">
  <p/>
<p><a href="{% url "actu:liste" %}" class="button alt">{% trans "Retour à la liste" %}</a></p>
{% if envoi %}<p>{% trans "Cette actualité a été enregistrée" %}.{% endif %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Enregistrer" %}" />
</form>
</div></div></div></section></section>
{% endblock %}

actu/templates/actu/delete_actu.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% block titre %}{% trans "Suppression d'une actualité" %}{% endblock %}
{% block content %}
<section id="create" class="main style3 secondary">
  <div class="content">

  <div style="float:left;width:70%;text-align:center;background:#ffff;align:center">
<div style="width:90%;text-align:left;display: inline-block;">
  <p/>
<form action="" method="post">
    {% csrf_token %}
<p><a href="{% url "actu:liste" %}" class="button alt">{% trans "Retour aux actualités" %}</a></p>
    <p>{% blocktrans with object=object %} Voulez vous vraiment supprimer l'actualité {{ object }}?{% endblocktrans %}</p>
    <input type="submit" value="{% trans "Oui" %}" />
</form>
</div></div></div></section>
{% endblock %}

actu/templates/actu/update_actu.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% block titre %}{% trans "Modification d'une actualité" %}{% endblock %}

{% block content %}
<section id="create" class="main style3 secondary">
  <div class="content">

  <div style="float:left;width:70%;text-align:center;background:#ffff;align:center">
<div style="width:90%;text-align:left;display: inline-block;">
  <p/>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Enregistrer" %}" />
</form>
</div></div></div></section>
{% endblock %}