actu/urls.py
from django.urls import path

from actu import views

app_name = "actu"
urlpatterns = [
    path("", views.ActuList.as_view(), name="liste"),
    path("ajouter", views.ActuCreate.as_view(), name="add_actu"),
    path("edition/<int:pk>", views.ActuUpdate.as_view(), name="edit_actu"),
    path("supprimer/<int:pk>", views.ActuDelete.as_view(), name="delete_actu"),
]

calendrier/urls.py
from django.urls import path

from . import views
from .views import EventDelete, EventUpdate

app_name = "calendrier"
urlpatterns = [
    path("", views.Agenda.as_view(), name="liste"),
    path("calendar", views.Home.as_view(), name="home"),
    path("new", views.CreateEvent.as_view(), name="create_event"),
    path("edition/<int:pk>", EventUpdate.as_view(), name="edit_event"),
    path("supprimer/<int:pk>", EventDelete.as_view(), name="delete_event"),
    path("<int:id>/changename", views.ChangeName.as_view(), name="change-doodle-name"),
    path("<int:id>/reponse", views.ReponseEvent.as_view(), name="reponse"),
    path("<int:pYear>/<int:pMonth>", views.Calendar.as_view(), name="view-month"),
    path("<int:id>", views.ViewEvent.as_view(), name="view-event"),
]

calendrier/models.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _

from gestion.models import OssiaUser

ANSWERS = (
    ("oui", _("Oui")),
    ("non", _("Non")),
    ("pe", _("Peut-etre")),
)


class Event(models.Model):

    nom = models.CharField(max_length=100)
    nomcourt = models.CharField(max_length=9, verbose_name=_("Nom court"))
    date = models.DateField()
    debut = models.TimeField()
    fin = models.TimeField(blank=True, null=True)
    slug = models.CharField(
        max_length=7, editable=False, unique=True, default=uuid.uuid1
    )
    lieu = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    description_en = models.TextField(blank=True)
    desc_users = models.TextField(
        blank=True,
        verbose_name=_("Infos (visible seulement des muscisien·ne·s)"),
        null=True,
    )
    desc_users_en = models.TextField(
        blank=True,
        verbose_name=_("Infos en anglais (visible seulement des muscisien·ne·s"),
        null=True,
    )
    CALENDRIER_CHOICES = [
        ("F", _("Visible seulement par les muscisiens")),
        ("T", _("Afficher dans le calendrier pour tous")),
        ("H", _("Hall of fame")),
        ("C", _("Visible seulement par les cheff·e·s")),
        ("D", _("Visible seulement par les cheff·e·s et sur l'agenda public")),
    ]
    calendrier = models.CharField(
        max_length=1,
        choices=CALENDRIER_CHOICES,
        default="F",
    )

    def __str__(self):
        return self.nom

    class Meta:
        verbose_name = _("Evenement")


class Participants(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    participant = models.ForeignKey(OssiaUser, on_delete=models.CASCADE)
    reponse = models.CharField(
        _("Réponse"), max_length=20, default="non", choices=ANSWERS
    )
    

calendrier/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from calendrier.models import Event, Participants
from gestion.models import OssiaUser


class ModifEventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ["slug"]
        widgets = {
            "description": forms.Textarea(
                attrs={"placeholder": _("facultatif, balises html supportées")}
            ),
            "date": forms.TextInput(attrs={"placeholder": "jj/mm/aaaa"}),
            "debut": forms.TextInput(attrs={"placeholder": "hh:mm"}),
            "fin": forms.TextInput(attrs={"placeholder": _("hh:mm facultatif")}),
        }


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ["slug"]
        widgets = {
            "nomcourt": forms.TextInput(attrs={"placeholder": _("9 caractères max")}),
            "description": forms.Textarea(
                attrs={"placeholder": _("facultatif, balises html supportées")}
            ),
            "date": forms.TextInput(attrs={"placeholder": "jj/mm/aaaa"}),
            "debut": forms.TextInput(attrs={"placeholder": "hh:mm"}),
            "fin": forms.TextInput(attrs={"placeholder": _("hh:mm facultatif")}),
        }


class ParticipantsForm(forms.ModelForm):
    class Meta:
        model = Participants
        fields = ("reponse",)


class ChangeDoodleName(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ChangeDoodleName, self).__init__(*args, **kwargs)
        self.fields["doodlename"].initial = self.instance.profile.get_doodlename()

    def save(self, *args, **kwargs):
        super(ChangeDoodleName, self).save(*args, **kwargs)
        self.instance.profile.doodlename = self.cleaned_data["doodlename"]
        self.instance.profile.save()
        self.instance.save()

    class Meta:
        model = OssiaUser
        fields = ("doodlename",)

calendrier/views.py
import random
import string
from calendar import monthrange
from collections import defaultdict
from datetime import date, datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.safestring import mark_safe
from django.views.generic import DeleteView, TemplateView, UpdateView

from actu.models import Actu
from calendrier.calend import EventCalendar
from calendrier.forms import (ChangeDoodleName, EventForm, ModifEventForm,
                              ParticipantsForm)
from calendrier.models import Event, Participants
from gestion.mixins import ChefRequiredMixin
from gestion.models import Photo


def generer(*args):
    caracteres = string.ascii_letters + string.digits
    aleatoire = [random.choice(caracteres) for _ in range(6)]
    return "".join(aleatoire)


def named_month(pMonthNumber):
    return date(1900, pMonthNumber, 1).strftime("%B")


class Agenda(TemplateView):
    template_name = "calendrier/agenda.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("calendrier:home")
        return super(Agenda, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lToday = datetime.today()
        context["photo"] = Photo.objects.filter(cat="liste").order_by("?").first()
        context["events_a_venir"] = (
            Event.objects.filter(date__gte=lToday)
            .exclude(calendrier__iexact="F")
            .exclude(calendrier__iexact="C")
            .order_by("date")
        )
        context["events_passe"] = (
            Event.objects.filter(date__lt=lToday)
            .filter(calendrier__iexact="H")
            .order_by("-date")
        )
        return context


class Calendar(LoginRequiredMixin, TemplateView):
    template_name = "calendrier/home.html"

    @property
    def pYear(self):
        return self.kwargs["pYear"]

    @property
    def pMonth(self):
        return self.kwargs["pMonth"]

    def get_context_data(self, **kwargs):
        context = super(Calendar, self).get_context_data(**kwargs)
        actu = Actu.objects.all()
        photo = Photo.objects.filter(cat="home").order_by("?").first()
        lToday = datetime.now()
        lYear = int(lToday.year)
        lMonth = int(lToday.month)
        lCalendarFromMonth = datetime(lYear, lMonth, 1)
        lCalendarToMonth = datetime(lYear, lMonth, monthrange(lYear, lMonth)[1])
        lEvents = Event.objects.filter(
            date__gte=lCalendarFromMonth, date__lte=lCalendarToMonth
        ).exclude(calendrier__iexact="C").exclude(calendrier__iexact="D")
        lEvents_chef = Event.objects.filter(
            date__gte=lCalendarFromMonth, date__lte=lCalendarToMonth
        )
        lCalendar = EventCalendar(lEvents).formatmonth(lYear, lMonth)
        lCalendar_chef = EventCalendar(lEvents_chef).formatmonth(lYear, lMonth)
        lPreviousYear = lYear
        lPreviousMonth = lMonth - 1
        if lPreviousMonth == 0:
            lPreviousMonth = 12
            lPreviousYear -= 1
        lNextYear = lYear
        lNextMonth = lMonth + 1
        if lNextMonth == 13:
            lNextMonth = 1
            lNextYear = lYear + 1
        lYearAfterThis = lYear + 1
        lYearBeforeThis = lYear - 1

        events_a_venir_not_answered = (
            Event.objects.filter(date__gte=lToday)
            .exclude(participants__participant=self.request.user.profile)
            .exclude(calendrier__iexact="C")
            .exclude(calendrier__iexact="D")
            .order_by("date")
        )
        events_a_venir_answered_yes = (
            Event.objects.filter(date__gte=lToday)
            .filter(
                Q(participants__participant=self.request.user.profile)
                & Q(participants__reponse="oui")
            )
            .exclude(calendrier__iexact="C")
            .exclude(calendrier__iexact="D")
            .order_by("date")
        )
        events_a_venir_answered_no = (
            Event.objects.filter(date__gte=lToday)
            .filter(
                Q(participants__participant=self.request.user.profile)
                & Q(participants__reponse="non")
            )
            .exclude(calendrier__iexact="C")
            .exclude(calendrier__iexact="D")
            .order_by("date")
        )
        events_a_venir_answered_pe = (
            Event.objects.filter(date__gte=lToday)
            .filter(
                Q(participants__participant=self.request.user.profile)
                & Q(participants__reponse="pe")
            )
            .exclude(calendrier__iexact="C")
            .exclude(calendrier__iexact="D")
            .order_by("date")
        )
        events_a_venir_chef = (
            Event.objects.filter(date__gte=lToday)
            .filter(calendrier__in=["C"])
            .order_by("date")
        )
        events_a_venir_chef_public = (
            Event.objects.filter(date__gte=lToday)
            .filter(calendrier__in=["D"])
            .order_by("date")
        )

        context["Calendar"] = mark_safe(lCalendar)
        context["Calendar_chef"] = mark_safe(lCalendar_chef)
        context["Month"] = lMonth
        context["MonthName"] = named_month(lMonth)
        context["Year"] = lYear
        context["PreviousMonth"] = lPreviousMonth
        context["PreviousMonthName"] = named_month(lPreviousMonth)
        context["PreviousYear"] = lPreviousYear
        context["NextMonth"] = lNextMonth
        context["NextMonthName"] = named_month(lNextMonth)
        context["NextYear"] = lNextYear
        context["YearBeforeThis"] = lYearBeforeThis
        context["YearAfterThis"] = lYearAfterThis
        context["events_a_venir_answered_yes"] = events_a_venir_answered_yes
        context["events_a_venir_answered_no"] = events_a_venir_answered_no
        context["events_a_venir_answered_pe"] = events_a_venir_answered_pe
        context["events_a_venir_not_answered"] = events_a_venir_not_answered
        context["events_a_venir_chef"] = events_a_venir_chef
        context["events_a_venir_chef_public"] = events_a_venir_chef_public
        context["actu"] = actu
        context["photo"] = photo
        return context


class Home(Calendar):
    lToday = datetime.now()


class ViewEvent(LoginRequiredMixin, TemplateView):
    template_name = "calendrier/view_event.html"

    def get_context_data(self, **kwargs):
        context = super(ViewEvent, self).get_context_data(**kwargs)
        event = get_object_or_404(Event, id=self.kwargs["id"])
        participants = event.participants_set.all()


        # Restricted event, only erneso users can see it
        if not self.request.user.is_authenticated and not event.calendrier:
            return redirect(reverse("calendrier:home"))

        # Count the number of occurences of each instrument
        instrument_count = defaultdict(lambda: (0, 0, 0, [], [], []))
        for participant in participants:
            instru = participant.participant.instru
            if instru == "Autre":
                instru = participant.participant.instru_autre
            
            no, sure, maybe, namesoui, namespe, namesnon = instrument_count[instru]

            if participant.reponse == "oui":

                namesoui += [participant.participant.get_doodlename()]
                instrument_count[instru] = (
                    no,
                    sure + 1,
                    maybe,
                    namesoui,
                    namespe,
                    namesnon,
                )
            elif participant.reponse == "pe":
                namespe += [participant.participant.get_doodlename()]
                instrument_count[instru] = (
                    no,
                    sure,
                    maybe + 1,
                    namesoui,
                    namespe,
                    namesnon,
                )
            else:
                namesnon += [participant.participant.get_doodlename()]
                instrument_count[instru] = (no+1,sure, maybe, namesoui, namespe, namesnon)

        instrument_count = [
            (instrument, no,sure, maybe, namesoui, namespe, namesnon)
            for instrument, (
                no,
                sure,
                maybe,
                namesoui,
                namespe,
                namesnon,
            ) in instrument_count.items()
        ]

        context["event"] = event
        context["instrument_count"] = instrument_count
        context["participants"] = participants
        context["nboui"] = len(participants.filter(reponse="oui"))
        context["nbpe"] = len(participants.filter(reponse="pe"))
        context["nbnon"] = len(participants.filter(reponse="non"))
        context["chef_only"] = (event.calendrier == "C")|(event.calendrier == "D")
        return context


class ChangeName(LoginRequiredMixin, TemplateView):
    form_class = ChangeDoodleName
    template_name = "calendrier/changename.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class(instance=self.request.user)
        context["id"] = self.kwargs["id"]
        return context

    def post(self, request, *args, **kwargs):
        success = False
        requbis = request.POST.copy()
        form = self.form_class(requbis, instance=request.user)
        if form.is_valid():
            form.save()
            success = True
            return redirect("calendrier:view-event", id=self.kwargs["id"])
        else:

calendrier/templates/calendrier/home.html
{% extends "gestion/base.html" %}
{% load static %}
{% load frenchmonth %}
{% load i18n %}
{% load translate %}
{% load autotranslate %}

{% get_current_language as current_language %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'css/calend.css' %}" />
{% endblock %}

{% block titre %}{% trans "Ossia : Agenda" %} {% endblock %}

{% block content %}

    <section id="home" class="main style1 secondary">
      <div class="content">
        {% if actu %}
        <div style="float:left;width:100%;text-align:center;background:rgb(102, 153, 255);align:center">
        <div style="width:90%;text-align:left;display: inline-block;">
          <p/>
            <h4> {% blocktrans count counter=actu|length %}Actualité des chefs:{% plural %}Actualités des chef·fe·s:{% endblocktrans %}</h4>
            <ul>
              {% for a in actu %}
              <li>{% autotranslate current_language a.text a.text_en %}</li>
              {% endfor %}
            </ul>
            </div>
              </div>
  <p/>

        {% endif %}
      <h4 style="text-align:left">{% trans "Agenda :" %} </h4>


        <div style="float:left;width:50%">
<table width="100%" style="background:rgba(102, 153, 255,0.25)">
    <tr>
        <td width="20%" align="left">
          &lt;&lt;
          {% if current_language == "fr" %}
          <a href="{% url "calendrier:view-month" PreviousYear PreviousMonth %}">{{PreviousMonthName|frenchmonth}} {{PreviousYear}}</a>
          {% else %}
            <a href="{% url "calendrier:view-month" PreviousYear PreviousMonth %}">{{PreviousMonthName}} {{PreviousYear}}</a>
          {% endif %}
        </td>
        <td width="20%" align="center"><a href="{% url "calendrier:home" %}">{% trans "Aujourd'hui" %}</a></td>
        <td width="20%" align="right">
          {% if current_language == "fr" %}
            <a href="{% url "calendrier:view-month" NextYear NextMonth %}">{{NextMonthName|frenchmonth}} {{NextYear}}</a> &gt;&gt;
            {% else %}
              <a href="{% url "calendrier:view-month" NextYear NextMonth %}">{{NextMonthName}} {{NextYear}}</a> &gt;&gt;
            {% endif %}
        </td>
    </tr>
</table>
<div id="calendar" style="background:rgba(102, 153, 255,0.25)">
  {% if user.is_superuser or user.profile.is_chef %}
  {% if current_language == "fr" %}
  {{Calendar_chef|translate}}
  {% else %}
  {{Calendar_chef}}
  {% endif %}
  {% else %}
  {% if current_language == "fr" %}
  {{Calendar|translate}}
  {% else %}
  {{Calendar}}
  {% endif %}
  {% endif%}
</div>
{% if user.is_superuser or user.profile.is_chef %}
<a href="{% url "calendrier:create_event" %}"><button>{% trans "Ajouter un évènement" %}</button></a>
{% endif %}
</div>
  <div style="float:right;width:45%;">
    {% if user.profile.is_chef_event or user.profile.is_chef %}
    {% if events_a_venir_chef %}
    <div class="box" style="background-color:#4169E1">
    <h1> {% blocktrans count counter=events_a_venir_chef|length %}Doodle seulement visible par les cheff·e·s :{% plural %}Doodles seulement visibles par les cheff·e·s :{% endblocktrans %} </h1>
    <div class="table-wrapper">
      <table class="default">
        <thead>
          <tr>
            <th>{% trans "Nom" %}</th>
            <th>{% trans "Date" %}</th>
            <th>{% trans "Lieu" %}</th>
          </tr>
        </thead>
          <tbody>
            {% for e in events_a_venir_chef %}
            <tr>
            <td><b><u><a href="{% url 'calendrier:view-event' e.id %}">{{ e.nom }}</a></u></b></td>

              <td>{% blocktrans with date=e.date debut=e.debut %}Le {{ date }} à {{ debut }} {% endblocktrans %} </td>
              <td> {{e.lieu}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    {% endif %}
    {% if events_a_venir_chef_public %}
    <div class="box" style="background-color:#a9008a">
    <h1> {% blocktrans count counter=events_a_venir_chef_public|length %}Doodle visible par les cheff·e·s et le public :{% plural %}Doodles seulement visibles par les cheff·e·s :{% endblocktrans %} </h1>
    <div class="table-wrapper">
      <table class="default">
        <thead>
          <tr>
            <th>{% trans "Nom" %}</th>
            <th>{% trans "Date" %}</th>
            <th>{% trans "Lieu" %}</th>
          </tr>
        </thead>
          <tbody>
            {% for e in events_a_venir_chef_public %}
            <tr>
            <td><b><u><a href="{% url 'calendrier:view-event' e.id %}">{{ e.nom }}</a></u></b></td>

              <td>{% blocktrans with date=e.date debut=e.debut %}Le {{ date }} à {{ debut }} {% endblocktrans %} </td>
              <td> {{e.lieu}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    {% endif %}
    {% endif %}
    {% if events_a_venir_not_answered %}
    <div class="box" style="background-color:#e4522f">
    <h1> {% blocktrans count counter=events_a_venir_not_answered|length %}Doodle à remplir !!!! :{% plural %}Doodles à remplir !!!! :{% endblocktrans %} </h1>
    <div class="table-wrapper">
      <table class="default">
        <thead>
          <tr>
            <th>{% trans "Nom" %}</th>
            <th>{% trans "Date" %}</th>
            <th>{% trans "Lieu" %}</th>
          </tr>
        </thead>
          <tbody>
            {% for e in events_a_venir_not_answered %}
            <tr>
            <td><b><u><a href="{% url 'calendrier:view-event' e.id %}">{{ e.nom }}</a></u></b></td>

              <td>{% blocktrans with date=e.date debut=e.debut %}Le {{ date }} à {{ debut }} {% endblocktrans %} </td>
              <td> {{e.lieu}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
  </div>
  {% endif %}
  {% if events_a_venir_answered_yes %}
  <div class="box" style="background-color:#d0fa98">

    <h1  >{% blocktrans count counter=events_a_venir_answered_yes|length %}Evénement auquel je compte participer (réponse Oui):{% plural %}Evénements auquels je compte participer (réponse Oui):{% endblocktrans %} </h1>

    <div class="table-wrapper">
      <table class="default" >
        <thead>
          <tr>
            <th  >{% trans "Nom" %}</th>
            <th  >{% trans "Date" %}</th>
            <th  >{% trans "Lieu" %}</th>
          </tr>
        </thead>
          <tbody>
            {% for e in events_a_venir_answered_yes %}
            <tr>
            <td ><b><u  ><a   href="{% url 'calendrier:view-event' e.id %}">{{ e.nom }}</a></u></b></td>

              <td > {% blocktrans with date=e.date debut=e.debut %}Le {{ date }} à {{ debut }} {% endblocktrans %} </td>
              <td > {{e.lieu}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
  </div>
  {% endif %}
  {% if events_a_venir_answered_pe %}
  <div class="box" style="background-color:#ffd98c">

      <h1  > {% blocktrans count counter=events_a_venir_answered_pe|length %}Evénement à confirmer (réponse Peut être):{% plural %}Evénements à confirmer (réponse Peut être):{% endblocktrans %} </h1>

      <div class="table-wrapper">
        <table class="default" >
          <thead>
            <tr>
              <th  >{% trans "Nom" %}</th>
              <th  >{% trans "Date" %}</th>
              <th  >{% trans "Lieu" %}</th>
            </tr>
          </thead>
            <tbody>
              {% for e in events_a_venir_answered_pe %}
              <tr>
              <td ><b><u  ><a   href="{% url 'calendrier:view-event' e.id %}">{{ e.nom }}</a></u></b></td>

                <td > {% blocktrans with date=e.date debut=e.debut %}Le {{ date }} à {{ debut }} {% endblocktrans %} </td>
                <td > {{e.lieu}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
  {% endif %}
  {% if events_a_venir_answered_no %}
  <div class="box" style="background-color:#f79583">

        <h1  > {% blocktrans count counter=events_a_venir_answered_no|length %}Evénement sans moi (réponse Non):{% plural %}Evénements sans moi (réponse Non):{% endblocktrans %} </h1>

        <div class="table-wrapper">
          <table class="default" >
            <thead>
              <tr>
                <th  >{% trans "Nom" %}</th>
                <th  >{% trans "Date" %}</th>
                <th  >{% trans "Lieu" %}</th>
              </tr>
            </thead>
              <tbody>
                {% for e in events_a_venir_answered_no %}
                <tr>
                <td ><b><u  ><a   href="{% url 'calendrier:view-event' e.id %}">{{ e.nom }}</a></u></b></td>

                  <td >{% blocktrans with date=e.date debut=e.debut %}Le {{ date }} à {{ debut }} {% endblocktrans %}</td>
                  <td > {{e.lieu}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
  {% endif %}

</div>
</section>

{% endblock %}

calendrier/templates/calendrier/view_event.html
{% extends "gestion/base.html" %}
{% load i18n %}
{% load autotranslate %}
{% get_current_language as current_language %}
{% block titre %}{{ event.nom.capitalize }}{% endblock %}

{% block content %}
<section id="home" class="main style1 secondary">
	<div class="content">
		<div id="viewevent" style="float:left;width:50%">

    <h2>{{ event.nom.capitalize }}</h2>

    <h4>
      {% blocktrans with date=event.date%} Le {{ date }}{% endblocktrans %}
      {% if event.fin %}
          {% blocktrans with debut=event.debut|time:"H:i" fin=event.fin|time:"H:i" %} de {{ debut}} à {{ fin }}{% endblocktrans %}
      {% else %}
        {% blocktrans with debut=event.debut|time:"H:i" %}  à {{ debut }}{% endblocktrans %}
      {% endif %}
    {% blocktrans with lieu=event.lieu %}- {{ lieu }}{% endblocktrans %}
    </h4>
    <h3>{% trans "Participants" %}</h3>
    <h4>{% blocktrans with nboui=nboui nbpe=nbpe nbnon=nbnon %}<b>{{ nboui }}</b> ont répondu oui, <b>{{ nbpe }}</b> peut-être, et <b>{{ nbnon }}</b> non{% endblocktrans %}</h4>
		{% if user.is_authenticated and event.desc_users %}

		<div class="box">
		{% autotranslate current_language event.desc_users event.desc_users_en %}

		</div>
		{% endif %}
<a href="{% url 'calendrier:reponse' event.id %}"><button>{% trans "Répondre à l'événement" %}</button></a>

          {% if not user.is_superuser or not user.profile.is_chef %}
          {% if chef_only %}
          {% trans "Cet événement est encore en construction ! Reviens plus tard." %}
          {% endif %}
          {% endif %}
          {% if user.is_superuser or user.profile.is_chef or not chef_only%}

</div>
<div style="float:left;width:50%">
{% if instrument_count %}

  <table class="table" width="100%"style="background: rgb(102, 153, 255);">
    <tr>
      <th >{% trans "Instrument" %}</th>
      <th width="20%">{% trans "Oui" %}</th>
      <th width="20%">{% trans "Peut-être" %}</th>
			<th width="20%">{% trans "Non" %}</th>
    </tr>
    {% for instrument, no, sure, maybe, namesoui, namespe,namesnon in instrument_count %}
      <tr>


            <td>
          <div class="spoilerDiv" onclick="ouvrirFermerSpoiler(this);" align="center">
              <span class="lienAfficher">	<u style="color:#ffffff">	<a style="cursor:pointer">{{ instrument }}</a> </u></span>
              <div class="spoiler">
                  <div class="contenuSpoiler">
                  <table style="background: #99bbff;" >
                      <tr>
                          <th>{% trans "Oui" %}</th>
                          <th>{% trans "Peut-être" %}</th>
													<th>{% trans "Non" %}</th>
                      </tr>
                      <td>
                          <ul>
                          {% for name in namesoui %}
                    <li>{{name}}</li>
                    {% endfor %}
                          </ul>
                      </td>
                         <td>
                          <ul>
                          {% for name in namespe %}
                    <li>{{name}}</li>
                    {% endfor %}
                          </ul>
													<ul>
													{% for name in namesnon %}
										<li>{{name}}</li>
										{% endfor %}
													</ul>
                      </td>

                  </table>
                  </div>
              </div>
          </div>
          </td>

        <td>{{ sure }}</td>
        <td>{{ maybe }}</td>
				<td>{{ no }}</td>
      </tr>
    {% endfor %}
  </table>

{% endif %}


{% if user.is_authenticated %}

  <div id="actions">    {% if user.profile.is_chef %}
        <a href="{% url "calendrier:edit_event" event.id %}"><button >{% trans "Modifier l'événement" %}</button></a> &nbsp <a href="{% url "calendrier:delete_event" event.id %}"><button>{% trans "Supprimer l'événement" %}</button></a
      {% endif %}
    <a href="{% url 'calendrier:change-doodle-name' event.id %}" ><button >{% trans "Changer mon nom pour le doodle" %}</button></a> &nbsp <a href="{% url 'calendrier:home' %}"><button>{% trans "Retour au calendrier" %}</button></a>
  </div>
	</div>

{% endif %}

{% endif %}
  </div>
</section>

{% endblock %}